SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

--
-- Structure of table `XIIIServer`
--
CREATE TABLE IF NOT EXISTS `XIIIServer` (
  `ID` int(11) NOT NULL,
  `SERVERIP` char(15) NOT NULL,
  `SERVERPORT` int(5) NOT NULL,
  `SERVERQUERY` int(5) NOT NULL,
  `SERVERCREATION` datetime NOT NULL,
  `SERVERVALIDTIME` datetime NOT NULL
) ENGINE=MyISAM AUTO_INCREMENT=10 DEFAULT CHARSET=latin1;

--
-- Index pour la table `XIIIServer`
--
ALTER TABLE `XIIIServer`
  ADD PRIMARY KEY (`ID`,`SERVERIP`,`SERVERPORT`,`SERVERQUERY`);

--
-- AUTO_INCREMENT pour la table `XIIIServer`
--
ALTER TABLE `XIIIServer`
  MODIFY `ID` int(11) NOT NULL AUTO_INCREMENT,AUTO_INCREMENT=10;
